services:
  selfieproxy-agent:
    image: ghcr.io/jeltechnologies/selfieproxy-reverseproxy:latest
    build: ./selfieproxy-reverseproxy
    container_name: selfieproxy-agent
    restart: unless-stopped
    env_file: .env
    command: ["agent", "-server", "${SELFIEPROXY_LISTENER}", "-secret", "${AGENT_SECRET}", "-agent-name", "${AGENT_NAME}", "-cert-dir", "/certmagic"]
    volumes:
      - ./data/boringproxy/certmagic:/certmagic
      - /etc/ssl/certs/:/etc/ssl/certs/:ro
